add build check in ci

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -28,9 +28,38 @@ jobs:
           res=$?
 
           if [ "${{ job.status }}" = "success" ]; then
-            echo "🔴 TESTS FAILED" >> $GITHUB_STEP_SUMMARY
-          else
             echo "🟢 TESTS PASSED" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "🔴 TESTS FAILED" >> $GITHUB_STEP_SUMMARY
+          fi
+
+  docker-build:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build server image
+        uses: docker/build-push-action@v5
+        with:
+          context: ./src
+          file: ./deploy/images/server/Dockerfile
+          push: false
+          tags: cachestore-server:latest
+          load: true
+          
+      - name: Test docker image
+        run: |
+          docker images
+          if docker inspect cachestore-server:latest &>/dev/null; then
+            echo "🟢 DOCKER BUILD PASSED" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "🔴 DOCKER BUILD FAILED" >> $GITHUB_STEP_SUMMARY
+            exit 1
           fi
 
 
